Update README.md
tuladhar/Python-for-SysAdmin-Part-I pull request #9
Opened 2020-10-08 19:11 UTC by meteora2002

finished the json file in simple language

this is my github contribution .feel free to give constructive feedbacks

2020-10-09 07:25 UTC, tuladhar commented
Congrats @meteora2002 on your first contribution. I suggest you to make README a bit more readable using correct formatting, currently, it does look rightly formatted.

2020-10-10 10:01 UTC, meteora2002 commented
done

2020-10-10 10:02 UTC, meteora2002 commented
@tuladhar please accept my pull requests

2020-10-10 14:03 UTC, tuladhar requested changes

2020-10-10 14:03 UTC, tuladhar commented on README.md
> +-json. load() takes a file object and returns the json object. A JSON object contains data in the form of key/value pair. The keys are strings and the values are the JSON types
Please remove the duplicate mention of json.load(), for e.g:

```suggestion
- `json.loads()` takes a file object and returns the json object. A JSON object contains data in the form of key/value pair. The keys are strings and the values are the JSON types
```

and remove duplicate json.dumps() in below lines as well.

2020-10-10 14:03 UTC, tuladhar commented on README.md
> +## THIS IS THE ENCODING DECODING LIST
Let's use table formatting for encoding and decoding list.

2020-10-10 14:03 UTC, tuladhar commented
Thanks @meteora2002 I've requested for some changes, please check.

2020-10-10 15:24 UTC, meteora2002 commented
@tuladhar please accept my pull requests

2020-10-12 06:25 UTC, meteora2002 commented
@tuladhar  please check my pull request

2020-10-12 07:34 UTC, tuladhar requested changes

2020-10-12 07:34 UTC, tuladhar commented on README.md
> +|  JSON|  Python |
Table is still not showing up correctly.

2020-10-12 07:34 UTC, tuladhar commented on README.md
> +## THIS IS THE ENCODING DECODING LIST
Let's use normal text for it, and remove the heading formatting.

2020-10-12 07:34 UTC, tuladhar commented on README.md
> +## other commands
Let's rename it to "Encoding functions"

2020-10-12 07:34 UTC, tuladhar commented on README.md
> +## note
Let's capitalize it.

2020-10-12 12:19 UTC, meteora2002 commented
done

2020-10-12 12:20 UTC, meteora2002 commented
@tuladhar please check my pull request

2020-10-13 06:19 UTC, tuladhar requested changes

2020-10-13 06:19 UTC, tuladhar commented on README.md
> +|  JSON |Python |
Table is still not showing. You can learn about it here:
- https://www.makeuseof.com/tag/create-markdown-table/

2020-10-13 06:21 UTC, tuladhar commented
Also, @meteora2002 let's remove the "coming soon" label from the contents table for JSON and add link.

<img width="246" alt="Screen Shot 2020-10-13 at 12 05 57" src="https://user-images.githubusercontent.com/5674762/95822891-749c2d80-0d4c-11eb-8265-0485060b3a22.png">

2020-10-13 07:29 UTC, tuladhar requested changes

2020-10-13 07:29 UTC, tuladhar commented on README.md
> -  8. [JSON Module](#exploring-json-module) ![Generic badge](https://img.shields.io/badge/Coming%20-Soon-blue)
Please fix the link and point to:
- https://github.com/meteora2002/Python-for-SysAdmin#exploring-json-module-exploring-json-module

2020-10-13 12:43 UTC, tuladhar approved these changes
Thanks @meteora2002 for your contributions. Looks good to merge!

2020-10-13 12:43 UTC, merged